### ISSUE TITLE
Pig Dice Game 구현하기

### ISSUE THREAD

**Issue by yjh0816** [Team-ggulggul/pig-dice-game#1]
## 요약
Pig Dice Game(PvE ver.)을 구현하겠습니다.

## 할일
- [x] pig-dice-game repo 생성하기
- [x] repo 각자 fork하기
- [x]  .gitignore 추가하기
- [x]  README.md 업데이트 하기
- [x] Pig Dice Game 구현을 위한 Pseudocode 작성하기
- [x] 작성한 Pseudocode를 토대로 Diagram 그리기
- [x] 작성한 Pseudocode를 토대로 Issues 작성하기
- [x] Issues 관리를 위한 Project 생성하기

## 참조
[Pig_(dice_game)](https://en.wikipedia.org/wiki/Pig_(dice_game))

**Comment by ulgoon** [comment]
할 일 들이 각각의 이슈라면 더 좋을 것 같아욤:)

**Comment by yjh0816** [comment]
> 할 일 들이 각각의 이슈라면 더 좋을 것 같아욤:)

I've done
